server:
  port: 5001 # 服务端口

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/masj7/spring-cloud-08-config-file.git
